/* Hijabia catalogue — abayas, kaftans & open kimonos.
   All imagery is FACE-FREE (garments on hangers, headless forms, flatlays,
   fabric detail, cropped product shots) and every URL is curl-verified
   (200 + image/*). Base Unsplash URLs; app.js appends sizing params. */
window.HIJABIA_MEDIA = {
  hero: { image: "https://images.unsplash.com/photo-1605450081927-6b40c11c661f", alt: "Flowing modest dresses and robes in a warm, styled boutique" },
  "banner-abaya": { image: "https://images.unsplash.com/photo-1519554318711-aaf73ece6ff9", alt: "Minimal charcoal abaya on a hanger against a clean white wall" },
  "banner-kaftan": { image: "https://images.unsplash.com/photo-1772474500365-c2c520545f44", alt: "Close-up of a black kaftan with floral beadwork on the neckline and cuff" },
  "banner-kimono": { image: "https://images.unsplash.com/photo-1662519951774-e8f89ea1200a", alt: "Row of flowing open robes on a rail in a softly lit dressing area" },
  about: { image: "https://images.unsplash.com/photo-1600376456587-b9ce4b52a372", alt: "Rolls of neutral-toned fabric leaning in a textile atelier" }
};

window.HIJABIA_PRODUCTS = [
  { id: 1, name: "Satin Drape Maxi Abaya", category: "Abaya", fabric: "Satin", price: 129, badge: "Bestseller",
    sizes: ["S", "M", "L", "XL"],
    colors: [{ name: "Black", hex: "#101012" }, { name: "Ivory", hex: "#F3EEE6" }],
    image: "https://images.unsplash.com/photo-1615809849790-438ce61b0cf7",
    alt: "Long flowing satin abaya hanging from a hanger by a window.",
    description: "A full-length satin-finish abaya photographed on the hanger, its long sleeves and floor-skimming hem catching the window light. Cut for graceful, head-turning drape at formal occasions." },

  { id: 2, name: "Beaded Evening Kaftan", category: "Kaftan", fabric: "Chiffon", price: 119,
    sizes: ["S", "M", "L", "XL"],
    colors: [{ name: "Black", hex: "#1A1A1A" }, { name: "Charcoal", hex: "#36393D" }, { name: "Onyx", hex: "#2B2B2B" }],
    image: "https://images.unsplash.com/photo-1657295766073-6be3510e5aa5",
    alt: "Black beaded evening kaftan hanging on a wooden hanger against a clean white wall.",
    description: "A floor-length black evening kaftan in fluid chiffon, scattered with tiny beadwork that catches the light. Photographed on the hanger so the soft drape and embellished bodice are clearly visible." },

  { id: 3, name: "Butterfly Embroidered Kimono", category: "Kimono", fabric: "Satin", price: 129, badge: "New",
    sizes: ["M", "L", "XL", "56\""],
    colors: [{ name: "Emerald", hex: "#3E7C4F" }, { name: "Olive", hex: "#6B7A3A" }, { name: "Charcoal", hex: "#3A3A3A" }],
    image: "https://images.unsplash.com/photo-1761724794887-b4713bab592b",
    alt: "Green silk open kimono with all-over butterfly embroidery on a dress form.",
    description: "A statement open kimono in lustrous green silk, embroidered all over with colourful butterflies and a contrast embellished yoke. Wide flowing sleeves make it a luxe layering piece." },

  { id: 4, name: "Beaded Cape Evening Abaya", category: "Abaya", fabric: "Georgette", price: 149, badge: "Limited",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [{ name: "Black", hex: "#0F0F11" }, { name: "Onyx", hex: "#1C1C1F" }],
    image: "https://images.unsplash.com/photo-1629936058756-db08ef906b0f",
    alt: "Black beaded cape-overlay gown with sheer sleeves on a headless mannequin.",
    description: "An evening abaya with a beaded cape overlay, sheer georgette sleeves and a jewelled waist tie for a dramatic occasion silhouette. Hand-embellished detailing across the cape catches the light beautifully." },

  { id: 5, name: "Sequin Embellished Kaftan", category: "Kaftan", fabric: "Georgette", price: 124,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [{ name: "Black", hex: "#181818" }, { name: "Gunmetal", hex: "#5A5D61" }, { name: "Silver", hex: "#B9BCC0" }],
    image: "https://images.unsplash.com/photo-1657295766148-6bdd569c663b",
    alt: "Black and silver sequin-embellished kaftans hanging side by side on wooden hangers.",
    description: "An occasion kaftan in flowing georgette with a hand-detailed panel of sequins and beadwork across the front. The metallic shimmer reads black-to-silver depending on the light." },

  { id: 6, name: "Lilac Striped Duster Robe", category: "Kimono", fabric: "Satin", price: 89,
    sizes: ["S", "M", "L", "XL"],
    colors: [{ name: "Lilac Grey", hex: "#B9B2C0" }, { name: "Silver Grey", hex: "#C7C7CE" }, { name: "Charcoal", hex: "#3C3A40" }],
    image: "https://images.unsplash.com/photo-1629936060120-e38e75bb2784",
    alt: "Lilac-grey striped satin open robe with a braided belt on a dress form.",
    description: "An open-front satin duster robe in shimmering lilac-grey stripes, finished with delicate trim down the front and a knotted braided belt. Light catches the sheen for a refined evening layer." },

  { id: 7, name: "Pleated Wrap Maxi Abaya", category: "Abaya", fabric: "Georgette", price: 89,
    sizes: ["S", "M", "L", "XL"],
    colors: [{ name: "Mocha", hex: "#A88A78" }, { name: "Dusty Rose", hex: "#C9A6A0" }, { name: "Mauve", hex: "#B89AA0" }],
    image: "https://images.unsplash.com/photo-1640923160720-35dddb6348ab",
    alt: "Mauve-mocha tiered wrap maxi abaya hanging on a wooden hanger.",
    description: "A soft mocha-mauve abaya-style maxi with a wrap bodice and gently tiered, pleated skirt for everyday modest elegance. The fluid georgette drapes beautifully and moves with you." },

  { id: 8, name: "Crochet Lace Resort Kaftan", category: "Kaftan", fabric: "Crepe", price: 96, badge: "New",
    sizes: ["S", "M", "L", "XL"],
    colors: [{ name: "Stone Grey", hex: "#8C8A85" }, { name: "Ivory", hex: "#EFE9DD" }, { name: "Taupe", hex: "#A8A097" }],
    image: "https://images.unsplash.com/photo-1668619322867-9654664e6a63",
    alt: "Long crochet lace kaftan hanging on a hanger in front of a bright window.",
    description: "A full-length lace kaftan with an allover scalloped crochet pattern and short flutter sleeves. The open lacework and soft A-line fall make it a romantic layer for warm-weather days." },

  { id: 9, name: "Ivory Lace Open Robe", category: "Kimono", fabric: "Lace", price: 76,
    sizes: ["XS", "S", "M", "L"],
    colors: [{ name: "Ivory", hex: "#F3ECDD" }, { name: "Cream", hex: "#EFE6D2" }, { name: "Beige", hex: "#E2D4BE" }],
    image: "https://images.unsplash.com/photo-1620900128850-b12749d73093",
    alt: "Ivory floral lace open robe laid flat with delicate styling props.",
    description: "Delicate ivory floral lace shapes this airy open robe, scalloped along the edges with fine satin ties. A romantic, lightweight layer for soft, modest styling." },

  { id: 10, name: "Tailored Structured Abaya", category: "Abaya", fabric: "Crepe", price: 115, badge: "Bestseller",
    sizes: ["XS", "S", "M", "L"],
    colors: [{ name: "Black", hex: "#0D0D0F" }, { name: "Espresso", hex: "#33271F" }],
    image: "https://images.unsplash.com/photo-1619203219004-83508ebb4a5e",
    alt: "Black tailored abaya on a structured dress form against a pale panelled wall.",
    description: "A structured, body-skimming abaya silhouette shown on a tailoring form to highlight its sculpted seams and clean lines. Crafted in premium crepe that holds a crisp, modest shape." },

  { id: 11, name: "Printed Floral Kaftan Robe", category: "Kaftan", fabric: "Silk", price: 89,
    sizes: ["S", "M", "L", "XL"],
    colors: [{ name: "Coral", hex: "#E9755E" }, { name: "Crimson", hex: "#B6303A" }, { name: "Blush", hex: "#F3B6AD" }],
    image: "https://images.unsplash.com/photo-1759579470279-0a647e2968b9",
    alt: "Coral and red floral-print silk kaftan robe hanging on a wooden wall.",
    description: "A wrap-style printed kaftan robe in lustrous silk, splashed with bold red parasol-and-blossom motifs over a coral ground. Tie-belted and free-flowing, it makes a vivid statement layer." },

  { id: 12, name: "Terracotta Lace Tie Robe", category: "Kimono", fabric: "Lace", price: 82,
    sizes: ["XS", "S", "M", "L"],
    colors: [{ name: "Terracotta", hex: "#B0492E" }, { name: "Burgundy", hex: "#7C2A2A" }, { name: "Dusty Rose", hex: "#C58A7E" }],
    image: "https://images.unsplash.com/photo-1624821377451-3a8ce189c3d6",
    alt: "Terracotta lace-trimmed open robe laid flat with satin tie fastenings.",
    description: "A warm terracotta open robe trimmed with scalloped floral lace and slim satin ties. The rich rust tone and soft drape make it a striking modest layering piece." },

  { id: 13, name: "Ivory Embroidered Occasion Abaya", category: "Abaya", fabric: "Chiffon", price: 144, badge: "Limited",
    sizes: ["S", "M", "L", "XL"],
    colors: [{ name: "Ivory", hex: "#F0E9DC" }, { name: "Beige", hex: "#D9C9A8" }, { name: "Champagne", hex: "#E2CFA6" }],
    image: "https://images.unsplash.com/photo-1623609163859-ca93c959b98a",
    alt: "Ivory all-over embroidered occasion gown on a headless mannequin.",
    description: "An ivory occasion abaya covered in tonal leaf embroidery and metallic threadwork for a soft, luminous finish. The fitted bodice and full skirt make it a statement piece for weddings and Eid." },

  { id: 14, name: "Printed Silk Kaftan", category: "Kaftan", fabric: "Silk", price: 112,
    sizes: ["S", "M", "L", "XL"],
    colors: [{ name: "Vermilion", hex: "#D8482B" }, { name: "Teal", hex: "#2F6D76" }, { name: "Blush Pink", hex: "#E7A9B0" }],
    image: "https://images.unsplash.com/photo-1609562041317-3c13618f1128",
    alt: "Rack of colourful patterned silk kaftan robes hanging together.",
    description: "A vibrantly printed silk kaftan drawn from a collection of richly patterned robes — swirls, blossoms and geometric motifs. The fluid silk drape makes it a striking occasion layer." },

  { id: 15, name: "Ivory Linen Duster Coat", category: "Kimono", fabric: "Linen", price: 94,
    sizes: ["S", "M", "L", "XL", "56\""],
    colors: [{ name: "Ivory", hex: "#EDE7DA" }, { name: "Stone", hex: "#D9CFBE" }, { name: "Beige", hex: "#CDBFA6" }],
    image: "https://images.unsplash.com/photo-1573675580296-266e838854f8",
    alt: "Ivory linen duster coat draped over a wooden stand in an elegant interior.",
    description: "A relaxed open-front duster in natural ivory linen, draping in soft folds for an effortless layer. Breathable and unstructured, it adds quiet elegance over any outfit." },

  { id: 16, name: "Classic Open-Front Abaya", category: "Abaya", fabric: "Nidha", price: 98,
    sizes: ["54\"", "56\"", "58\"", "60\""],
    colors: [{ name: "Black", hex: "#121214" }, { name: "Graphite", hex: "#3A3A3D" }],
    image: "https://images.unsplash.com/photo-1587293823642-c25dd4a33f80",
    alt: "Black flowing abayas hanging on wooden hangers on a boutique rail.",
    description: "A minimalist everyday Nidha abaya shown on the rail, prized for its matte drape and fluid movement. The soft, breathable weave keeps its shape from morning errands to evening gatherings." },

  { id: 17, name: "Burgundy Satin Kaftan", category: "Kaftan", fabric: "Satin", price: 99,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [{ name: "Burgundy", hex: "#7C1023" }, { name: "Wine", hex: "#5E0E1C" }, { name: "Deep Red", hex: "#9B1B2E" }],
    image: "https://images.unsplash.com/photo-1518893063132-36e46dbe2428",
    alt: "Lustrous deep red satin fabric draped in soft folds.",
    description: "A fluid evening kaftan cut from deep burgundy satin with a high-sheen finish that pools and ripples with movement. The rich red tone makes it a luxe choice for special occasions." },

  { id: 18, name: "Natural Linen Open Duster", category: "Kimono", fabric: "Linen", price: 88,
    sizes: ["M", "L", "XL", "58\""],
    colors: [{ name: "Natural", hex: "#D8CDB6" }, { name: "Oatmeal", hex: "#CFC2A6" }, { name: "Stone Grey", hex: "#B7AE9C" }],
    image: "https://images.unsplash.com/photo-1565532070333-43edd7d75c90",
    alt: "Natural linen open duster on a wooden hanger in dramatic light.",
    description: "An unlined open duster in textured natural linen, hung to show its long, fluid lines. The earthy oatmeal tone and soft hand make it an easy everyday layer." },

  { id: 19, name: "Lace Overlay Formal Abaya", category: "Abaya", fabric: "Chiffon", price: 119,
    sizes: ["XS", "S", "M", "L"],
    colors: [{ name: "Black", hex: "#121215" }, { name: "Midnight", hex: "#1A1A24" }],
    image: "https://images.unsplash.com/photo-1623609163841-5e69d8c62cc7",
    alt: "Black lace formal gown with a scalloped neckline on a headless mannequin.",
    description: "A romantic black abaya with a delicate lace overlay and a softly scalloped neckline, photographed in moody black-and-white. The layered chiffon skirt adds graceful volume for evening wear." },

  { id: 20, name: "Emerald Satin Kaftan", category: "Kaftan", fabric: "Satin", price: 105, badge: "New",
    sizes: ["S", "M", "L", "XL"],
    colors: [{ name: "Emerald", hex: "#0F5A52" }, { name: "Deep Teal", hex: "#0C4B4F" }, { name: "Forest", hex: "#123E36" }],
    image: "https://images.unsplash.com/photo-1612744192242-35cd7a7d35e6",
    alt: "Deep emerald satin fabric draped in glossy folds.",
    description: "An elegant kaftan in deep emerald satin, its jewel-toned sheen catching light across every fold. The smooth, weighty drape gives the silhouette a refined, occasion-ready presence." },

  { id: 21, name: "Beige Crepe Trench Duster", category: "Kimono", fabric: "Crepe", price: 106,
    sizes: ["S", "M", "L", "XL"],
    colors: [{ name: "Beige", hex: "#D8C8B0" }, { name: "Camel", hex: "#B89B73" }, { name: "Charcoal", hex: "#3B3A38" }],
    image: "https://images.unsplash.com/photo-1722859031306-4c81e8d83957",
    alt: "Beige crepe trench-style duster on a wooden hanger against panelling.",
    description: "A polished open-front trench duster in soft beige crepe with a structured collar and clean lines. Tailored yet fluid, it layers elegantly for a modest, put-together look." },

  { id: 22, name: "Jacquard Belted Abaya", category: "Abaya", fabric: "Satin", price: 134, badge: "Bestseller",
    sizes: ["M", "L", "XL", "XXL"],
    colors: [{ name: "Ivory", hex: "#EFE7DA" }, { name: "Champagne", hex: "#E4D4B8" }, { name: "Gold", hex: "#C8A75B" }],
    image: "https://images.unsplash.com/photo-1742384194806-2a87f385345f",
    alt: "Close-up of an ivory jacquard abaya with gold braid trim and a slim belt.",
    description: "A luxe ivory satin-jacquard abaya trimmed in gold cording with a slim jewelled belt, detailing the bell sleeves and ornate placket. An elegant choice for celebrations and Eid." },

  { id: 23, name: "Linen Boutique Kaftan", category: "Kaftan", fabric: "Linen", price: 84,
    sizes: ["S", "M", "L", "XL"],
    colors: [{ name: "Black", hex: "#1B1B1B" }, { name: "Charcoal", hex: "#3A3A3A" }, { name: "Slate", hex: "#4D4F52" }],
    image: "https://images.unsplash.com/photo-1707311193851-557106099673",
    alt: "Black flowy linen kaftan on a wooden hanger against a styled pale wall.",
    description: "A relaxed black linen kaftan with a gathered waist and a gentle V-neck. Breathable and unstructured, it layers easily and travels well — an everyday modest staple." },

  { id: 24, name: "Mustard Open Long Coat", category: "Kimono", fabric: "Crepe", price: 112,
    sizes: ["M", "L", "XL", "58\""],
    colors: [{ name: "Mustard", hex: "#C99A2E" }, { name: "Olive", hex: "#7E7233" }, { name: "Camel", hex: "#B0894F" }],
    image: "https://images.unsplash.com/photo-1623854156816-4c4fc355ffc7",
    alt: "Mustard open-front long coat hanging on a rustic wooden wall.",
    description: "A cosy open-front long coat in warm mustard with patch pockets and a soft collar. The rich golden tone brings warmth to cooler-weather modest layering." },

  { id: 25, name: "A-Line Minimalist Abaya", category: "Abaya", fabric: "Jersey", price: 79, badge: "Bestseller",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [{ name: "Black", hex: "#0F0F11" }, { name: "Charcoal", hex: "#2C2C30" }],
    image: "https://images.unsplash.com/photo-1629935226757-6e22f6ef9ac1",
    alt: "A row of black dress-form mannequins against a white studio wall.",
    description: "Our minimalist A-line jersey abaya, celebrating clean, soft-stretch comfort that flatters every figure. An effortless everyday staple in our most versatile fabric." },

  { id: 26, name: "Woven Textured Kaftan", category: "Kaftan", fabric: "Linen", price: 78,
    sizes: ["M", "L", "XL", "XXL"],
    colors: [{ name: "Grey Marl", hex: "#9B9A96" }, { name: "Indigo", hex: "#2F3D52" }, { name: "Natural", hex: "#CFC6B4" }],
    image: "https://images.unsplash.com/photo-1706795042826-50f7e624ec80",
    alt: "Row of woven textured long tunic kaftans hanging on a wall display.",
    description: "An artisan-woven long kaftan in textured linen-blend yarns, in marled grey, indigo and natural tones. The loose tunic cut and nubby weave give it an easy, handcrafted character." },

  { id: 27, name: "Cream Lace Layering Robe", category: "Kimono", fabric: "Lace", price: 72,
    sizes: ["S", "M", "L", "XL"],
    colors: [{ name: "Cream", hex: "#EDE4D1" }, { name: "Ivory", hex: "#F4EEE0" }, { name: "Dusty Rose", hex: "#C9A9A0" }],
    image: "https://images.unsplash.com/photo-1620900161361-465d68a8ba0f",
    alt: "Cream floral lace open robe flatlay with a satin under-layer.",
    description: "A softly scalloped cream lace robe with intricate floral motifs and a satin under-layer. Light and breathable, it drapes beautifully as a delicate open layer." },

  { id: 28, name: "Blush Chiffon Open Abaya", category: "Abaya", fabric: "Chiffon", price: 98, badge: "New",
    sizes: ["S", "M", "L", "XL", "54\""],
    colors: [{ name: "Blush Beige", hex: "#E7D6C7" }, { name: "Mocha", hex: "#8B6F5C" }, { name: "Ivory", hex: "#F4EDE3" }],
    image: "https://images.unsplash.com/photo-1760083545495-b297b1690672",
    alt: "Blush chiffon open-front abaya with a self-tie belt and floral detailing.",
    description: "A softly draping open-front abaya in blush chiffon with a self-tie waist and delicate floral embroidery along the panels. Flows in airy layers for an elegant, modest silhouette." },

  { id: 29, name: "Dusty Rose Silk Kaftan", category: "Kaftan", fabric: "Silk", price: 102,
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: [{ name: "Dusty Rose", hex: "#C98A93" }, { name: "Mauve", hex: "#B07F8B" }, { name: "Blush", hex: "#E3B8BD" }],
    image: "https://images.unsplash.com/photo-1617055407123-3d7130c1f940",
    alt: "Soft dusty rose silk fabric draped in flowing folds.",
    description: "A softly draping silk kaftan in muted dusty rose, with a gentle satin-back lustre that lends quiet elegance. The fluid fall of the fabric flatters every figure and feels effortless to wear." }
];
