/* Hijabia x Hijabi MV — combined catalogue. Two brands, one storefront.
   Hijabia = abayas/kaftans/outerwear; Hijabi MV = hijabs/scarves/shawls.
   All imagery is FACE-FREE and every URL is curl-verified (200 + image/*). */
window.HIJABIA_MEDIA = {
  hero: { image: "https://images.unsplash.com/photo-1760083545495-b297b1690672", alt: "Blush long-sleeve abaya with embroidery on a form in a soft studio" },
  "banner-abaya": { image: "https://images.unsplash.com/photo-1608686862407-140903f9f149", alt: "Black long-sleeve abayas on featureless white mannequins" },
  "banner-kaftan": { image: "https://images.unsplash.com/photo-1632465215097-20ea7a021906", alt: "Yellow long-sleeve kaftan gown on a faceless dress form" },
  "banner-outerwear": { image: "https://images.unsplash.com/photo-1630962071084-315a960d1409", alt: "Long modest robes and coats on faceless mannequins" },
  "banner-hijab": { image: "https://images.unsplash.com/photo-1625471592808-3b848a6e9ffd", alt: "Folded solid-colour hijabs stacked by shade" },
  "banner-scarf": { image: "https://images.unsplash.com/photo-1571498521264-5fcaa7f8edf4", alt: "Colourful gauze scarves hanging in a row" },
  "banner-shawl": { image: "https://images.unsplash.com/photo-1545042746-ec9e5a59b359", alt: "Neatly folded soft shawls stacked in calm tones" },
  about: { image: "https://images.unsplash.com/photo-1507434745378-235a6297156b", alt: "Rolls of patterned fabric stacked in a textile atelier" }
};

window.HIJABIA_PRODUCTS = [
  { id: 1, brand: "Hijabia", name: "Onyx Blossom Embroidered Abaya", category: "Abaya", fabric: "Crepe", price: 139, badge: "New",
    sizes: ["52\"", "54\"", "56\"", "58\""],
    colors: [{ name: "Jet Black", hex: "#0E0E10" }, { name: "Sage Thread", hex: "#8A8B6E" }],
    image: "https://images.unsplash.com/photo-1772474500365-c2c520545f44",
    alt: "Black open-front abaya with sage floral embroidery on the neckline and cuffs.",
    description: "An open-front black abaya in weighty crepe, framed by hand-worked sage floral embroidery along the neckline and bell cuffs. Long sleeves and a clean drape layer beautifully over an inner dress." },

  { id: 2, brand: "Hijabi MV", name: "Signature Crinkle Hijab Bundle", category: "Hijab", fabric: "Viscose", price: 29, badge: "Bestseller",
    sizes: ["Maxi (200x75cm)", "Standard (180x70cm)"],
    colors: [{ name: "Blush Nude", hex: "#D9A38C" }, { name: "Berry Wine", hex: "#8E2C45" }, { name: "Mustard", hex: "#E2B233" }, { name: "Soft Lilac", hex: "#C7AEC0" }],
    image: "https://images.unsplash.com/photo-1652701666551-9df39e7cdb04",
    alt: "Rolled crinkle hijabs in a multicolour bundle.",
    description: "A curated bundle of crinkle-textured hijabs rolled into a soft rosette of colour. Lightweight, breathable viscose with a forgiving crepe finish that drapes without pinning." },

  { id: 3, brand: "Hijabia", name: "Marigold Embellished Kaftan", category: "Kaftan", fabric: "Crepe", price: 119, badge: "Bestseller",
    sizes: ["S", "M", "L", "XL"],
    colors: [{ name: "Marigold", hex: "#E5B500" }, { name: "Saffron", hex: "#D99000" }],
    image: "https://images.unsplash.com/photo-1632465215097-20ea7a021906",
    alt: "Yellow long-sleeve embroidered kaftan on a faceless dress form.",
    description: "A radiant marigold kaftan in fluid crepe with floral shoulder embellishment and a centre placket. Full-length sleeves and an unbroken floor-sweeping line give fully covered elegance." },

  { id: 4, brand: "Hijabi MV", name: "Bazaar Print Scarf Collection", category: "Scarf", fabric: "Viscose", price: 24, badge: "New",
    sizes: ["Standard (180x70cm)", "Long (180x65cm)"],
    colors: [{ name: "Cobalt", hex: "#2C5FA8" }, { name: "Coral", hex: "#E97A5B" }, { name: "Teal", hex: "#1F9E96" }, { name: "Magenta", hex: "#C23A78" }],
    image: "https://images.unsplash.com/photo-1545153252-0e2e698f0330",
    alt: "Rows of patterned printed scarves hanging on a stall display.",
    description: "Vibrant printed scarves in bazaar-inspired patterns, hung and knotted ready to choose. Fluid viscose that catches the light and ties into any look." },

  { id: 5, brand: "Hijabia", name: "Mustard Boiled-Wool Coat", category: "Outerwear", fabric: "Wool", price: 124, badge: "New",
    sizes: ["S", "M", "L"],
    colors: [{ name: "Mustard", hex: "#D9A521" }, { name: "Ochre", hex: "#C98A18" }, { name: "Camel", hex: "#C19A6B" }],
    image: "https://images.unsplash.com/photo-1565532070333-43edd7d75c90",
    alt: "Mustard boiled-wool long coat with long sleeves on a hanger.",
    description: "A cosy boiled-wool coat in warm mustard, with a high funnel neck, long sleeves and a dense opaque weave. A snug modest outer layer with patch pockets and a centre-front zip." },

  { id: 6, brand: "Hijabi MV", name: "Folded Linen-Touch Shawl", category: "Shawl", fabric: "Cotton", price: 26,
    sizes: ["Maxi (200x75cm)", "Oversized (200x100cm)"],
    colors: [{ name: "Chambray", hex: "#9FB0C4" }, { name: "Powder Blue", hex: "#C5D2DD" }, { name: "Dusty Rose", hex: "#C99A95" }],
    image: "https://images.unsplash.com/photo-1545042746-ec9e5a59b359",
    alt: "Neatly folded soft cotton shawls stacked in blue and pink tones.",
    description: "Softly folded cotton shawls with a relaxed linen-look weave and frayed selvedge. Generously sized for full coverage that stays breathable through the day." },

  { id: 7, brand: "Hijabia", name: "Crystal Trim Statement Abaya", category: "Abaya", fabric: "Nidha", price: 145,
    sizes: ["54\"", "56\"", "58\"", "60\""],
    colors: [{ name: "Midnight Black", hex: "#101014" }, { name: "Crystal Silver", hex: "#C9C7CC" }],
    image: "https://images.unsplash.com/photo-1772474578035-bebcd90b355d",
    alt: "Black open abaya edged with crystal and pearl beading down the front and cuffs.",
    description: "A black nidha abaya lined with a continuous run of crystal and pearl beading along the front opening and long sleeve cuffs. A refined, fully covering evening piece that holds its structure." },

  { id: 8, brand: "Hijabi MV", name: "Colour Block Folded Hijab Stack", category: "Hijab", fabric: "Cotton", price: 23,
    sizes: ["Standard (180x70cm)", "Maxi (200x75cm)"],
    colors: [{ name: "Aqua", hex: "#7FD4CF" }, { name: "Olive", hex: "#7E8C4A" }, { name: "Emerald", hex: "#2E8B57" }, { name: "Cocoa", hex: "#5A3A2E" }],
    image: "https://images.unsplash.com/photo-1625471592808-3b848a6e9ffd",
    alt: "Neatly folded solid-colour cotton hijabs stacked from aqua to brown.",
    description: "A tidy stack of solid-colour cotton hijabs from cool aqua to warm cocoa. Matte, opaque cotton with a soft hand and clean edges — an easy no-fuss daily wrap." },

  { id: 9, brand: "Hijabia", name: "Amber Floral Hooded Kaftan", category: "Kaftan", fabric: "Crepe", price: 124,
    sizes: ["M", "L", "XL"],
    colors: [{ name: "Amber Gold", hex: "#D6911F" }, { name: "Honey", hex: "#C77C1A" }],
    image: "https://images.unsplash.com/photo-1629936060124-4606d55822ce",
    alt: "Amber-gold long-sleeve kaftan with floral embroidery on a faceless dress form.",
    description: "An amber-gold kaftan with mirror-and-floral embroidery framing the chest and a slim braided placket. Long sleeves and a flowing opaque cut shown in full on a form." },

  { id: 10, brand: "Hijabi MV", name: "Rainbow Gauze Scarf Rack", category: "Scarf", fabric: "Cotton", price: 21,
    sizes: ["Long (180x65cm)", "Standard (180x70cm)"],
    colors: [{ name: "Marigold", hex: "#E5A21F" }, { name: "Periwinkle", hex: "#7E7FB8" }, { name: "Crimson", hex: "#B22B4A" }, { name: "Sand", hex: "#C9A877" }],
    image: "https://images.unsplash.com/photo-1571498521264-5fcaa7f8edf4",
    alt: "A spectrum of lightweight gauze scarves hung in rainbow order.",
    description: "A full spectrum of crinkled gauze scarves in rainbow order. Airy open-weave cotton that breathes in the heat and wraps light as a whisper." },

  { id: 11, brand: "Hijabia", name: "Atelier Linen Duster Coat", category: "Outerwear", fabric: "Linen", price: 112,
    sizes: ["S", "M", "L", "XL"],
    colors: [{ name: "Ecru", hex: "#EDE6D6" }, { name: "Stone", hex: "#D6CCBA" }, { name: "Sand", hex: "#CDB99E" }],
    image: "https://images.unsplash.com/photo-1604506847073-4a8e18e07d92",
    alt: "Cream linen long duster coats with long sleeves on a coat stand.",
    description: "A relaxed, breathable linen duster for warm-weather modest dressing. Long sleeves and a below-the-knee length give full coverage; an easy open layer over abayas and tunics." },

  { id: 12, brand: "Hijabi MV", name: "Cloud Drape Satin Shawl", category: "Shawl", fabric: "Satin", price: 30,
    sizes: ["Oversized (200x100cm)", "Maxi (200x75cm)"],
    colors: [{ name: "Sky Blue", hex: "#A8C2DC" }, { name: "Ice", hex: "#CFDEEA" }],
    image: "https://images.unsplash.com/photo-1676893140053-9b74ecfe79fe",
    alt: "Light blue satin shawl draped and floating over a pale background.",
    description: "A fluid satin shawl caught mid-drape, all soft sheen and weightless movement. Smooth and cool to the touch, oversized for full, flowing coverage." },

  { id: 13, brand: "Hijabia", name: "Emerald Goldwork Abaya", category: "Abaya", fabric: "Satin", price: 142,
    sizes: ["54\"", "56\"", "58\""],
    colors: [{ name: "Black Satin", hex: "#131316" }, { name: "Antique Gold", hex: "#B68A3C" }, { name: "Emerald", hex: "#1F6F54" }],
    image: "https://images.unsplash.com/photo-1739829417987-28d43f9a6b49",
    alt: "Black satin abaya sleeve with raised gold and emerald goldwork embroidery.",
    description: "A black satin abaya showcasing dimensional goldwork embroidery in emerald and antique gold along the long sleeve and front. A heritage occasion piece with a polished, full-coverage finish." },

  { id: 14, brand: "Hijabi MV", name: "Shimmer Glitter Chiffon Hijab", category: "Hijab", fabric: "Chiffon", price: 32, badge: "New",
    sizes: ["Maxi (200x75cm)", "Standard (180x70cm)"],
    colors: [{ name: "Rose Shimmer", hex: "#D58AA3" }, { name: "Soft Pink", hex: "#E2AFC0" }],
    image: "https://images.unsplash.com/photo-1627051882057-2e7ca9a2f96a",
    alt: "Pink chiffon hijab with fine glitter shimmer draped in soft folds.",
    description: "An occasion hijab in glitter-flecked chiffon that catches the light with every movement. Fluid and luminous, cut maxi for graceful draping at celebrations." },

  { id: 15, brand: "Hijabia", name: "Plum Braided Kaftan", category: "Kaftan", fabric: "Satin", price: 99,
    sizes: ["S", "M", "L", "XL"],
    colors: [{ name: "Deep Plum", hex: "#6B2A52" }, { name: "Aubergine", hex: "#4E1E3D" }],
    image: "https://images.unsplash.com/photo-1629936058792-4976e99fb6aa",
    alt: "Plum satin long-sleeve kaftan with tonal braided trim on a faceless dress form.",
    description: "A deep-plum satin kaftan with tonal braided cord trim along the placket and neckline. Minimal yet rich, with long sleeves and a smooth full-length drape." },

  { id: 16, brand: "Hijabi MV", name: "Aurelia Pleated Silk Scarf", category: "Scarf", fabric: "Silk", price: 38,
    sizes: ["One Size", "Long (180x65cm)"],
    colors: [{ name: "Peach Blush", hex: "#F2C9A8" }, { name: "Soft Sand", hex: "#E8D6C2" }, { name: "Charcoal", hex: "#3A3A38" }],
    image: "https://images.unsplash.com/photo-1609451043305-745f798b51a3",
    alt: "Peach silk scarf draped softly across a styled flatlay.",
    description: "A fluid peach silk scarf with a delicate self-print in a soft styled flatlay. The liquid drape and gentle sheen make it an effortless lightweight layer." },

  { id: 17, brand: "Hijabia", name: "Wardrobe Edit Wool Coat", category: "Outerwear", fabric: "Wool", price: 116,
    sizes: ["XS", "S", "M", "L"],
    colors: [{ name: "Oatmeal", hex: "#D9CDB8" }, { name: "Heather Grey", hex: "#9A958C" }, { name: "Taupe", hex: "#B7A78F" }],
    image: "https://images.unsplash.com/photo-1604882767135-b41fac508fff",
    alt: "Neutral wool long coats with long sleeves on a wardrobe rail.",
    description: "A soft neutral wool coat from our wardrobe-staple edit. Long sleeves and a longline drop keep things modest and warm, in muted oatmeal and heather tones." },

  { id: 18, brand: "Hijabi MV", name: "Saffron Crochet Shawl", category: "Shawl", fabric: "Modal", price: 42,
    sizes: ["One Size", "Standard (180x70cm)"],
    colors: [{ name: "Saffron Gold", hex: "#D9A441" }, { name: "Honey", hex: "#C68B2C" }],
    image: "https://images.unsplash.com/photo-1622648147611-e817249f3b73",
    alt: "Folded mustard-gold open-weave crochet shawl on white planks.",
    description: "A breezy open-weave shawl in warm saffron, light to fold yet roomy to drape. The airy crochet keeps it cool while adding handcrafted texture." },

  { id: 19, brand: "Hijabia", name: "Wildflower Print Maxi Abaya", category: "Abaya", fabric: "Linen", price: 89,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [{ name: "Olive Print", hex: "#7A7444" }, { name: "Dusk Blue", hex: "#6B7B96" }],
    image: "https://images.unsplash.com/photo-1739474019626-526d6d0dbcea",
    alt: "Olive floral-print long-sleeve maxi abaya laid flat with matching sandals.",
    description: "An olive wildflower-print maxi abaya in soft linen, cut as a buttoned A-line robe with long cuffed sleeves. An easy, fully covering everyday piece in a breathable opaque weave." },

  { id: 20, brand: "Hijabi MV", name: "Emerald Silk-Touch Hijab", category: "Hijab", fabric: "Satin", price: 33,
    sizes: ["Maxi (200x75cm)", "Standard (180x70cm)"],
    colors: [{ name: "Emerald", hex: "#2E9E6B" }, { name: "Jade", hex: "#4FB286" }],
    image: "https://images.unsplash.com/photo-1527167598984-8802d8028eea",
    alt: "Emerald green satin hijab draped in lustrous folds.",
    description: "A lustrous satin-finish hijab in deep emerald, shown in soft sculptural folds. Cool, smooth and richly coloured with a subtle sheen for special occasions." },

  { id: 21, brand: "Hijabia", name: "Ochre Heritage Kaftan", category: "Kaftan", fabric: "Crepe", price: 116,
    sizes: ["M", "L", "XL", "XXL"],
    colors: [{ name: "Ochre", hex: "#C9821C" }, { name: "Burnt Copper", hex: "#A65E1E" }],
    image: "https://images.unsplash.com/photo-1629936060095-044c1e77fa7d",
    alt: "Ochre long-sleeve kaftan with silver floral embroidery on a faceless dress form.",
    description: "An ochre crepe kaftan with silver-threaded floral embroidery across the chest and a braided centre seam. A warm, statement long-sleeve robe shown in full on a form." },

  { id: 22, brand: "Hijabi MV", name: "Carnival Print Twill Scarf", category: "Scarf", fabric: "Twill", price: 42,
    sizes: ["One Size", "Long (180x65cm)"],
    colors: [{ name: "Fuchsia", hex: "#D64C8E" }, { name: "Lime", hex: "#7FB23C" }, { name: "Tangerine", hex: "#E8761F" }],
    image: "https://images.unsplash.com/photo-1562176603-48b2cf0d96b3",
    alt: "Vibrant abstract multicolour print scarf knotted over a rail.",
    description: "A bold abstract-print twill scarf in fuchsia, lime and tangerine, knotted over a rail. The structured twill weave holds crisp folds for statement styling." },

  { id: 23, brand: "Hijabia", name: "Cold-Weather Longline Coat", category: "Outerwear", fabric: "Wool", price: 108,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [{ name: "Forest", hex: "#3B4A3A" }, { name: "Black", hex: "#1F1F1F" }, { name: "Rust", hex: "#A65A2E" }],
    image: "https://images.unsplash.com/photo-1649433911119-7cf48b3e8f50",
    alt: "Long wool cold-weather coats with long sleeves on a rack.",
    description: "A warm longline cold-weather coat for full coverage. Long sleeves, a high collar and an ankle-skimming cut keep you wrapped up, in deep forest and rust tones." },

  { id: 24, brand: "Hijabi MV", name: "Silver Mist Pashmina", category: "Shawl", fabric: "Pashmina", price: 58, badge: "Limited",
    sizes: ["Maxi (200x75cm)", "Long (180x65cm)"],
    colors: [{ name: "Silver Mist", hex: "#B9BDB6" }, { name: "Sage Grey", hex: "#9AA199" }],
    image: "https://images.unsplash.com/photo-1595421638746-4ee59299e5f3",
    alt: "Soft grey pashmina shawl with fringed ends, draped on a white surface.",
    description: "A featherlight pashmina in cool silver-grey, finished with delicate fringe. It folds to almost nothing yet opens into a generous wrap or soft hijab drape." },

  { id: 25, brand: "Hijabia", name: "Layla Crepe Wrap Abaya", category: "Abaya", fabric: "Crepe", price: 118, badge: "Bestseller",
    sizes: ["52\"", "54\"", "56\"", "58\""],
    colors: [{ name: "Onyx Black", hex: "#1A1A1A" }, { name: "Stone Grey", hex: "#7C7B78" }],
    image: "https://images.unsplash.com/photo-1686545231817-0a4afb052de8",
    alt: "Floor-length black crepe abaya with long sleeves, shown from behind.",
    description: "A flowing floor-length crepe abaya with a clean draped silhouette and full-length sleeves. Cut for complete coverage and effortless movement in soft opaque folds." },

  { id: 26, brand: "Hijabi MV", name: "Heritage Print Folded Hijab Set", category: "Hijab", fabric: "Cotton", price: 22,
    sizes: ["Square (110x110cm)", "Standard (180x70cm)"],
    colors: [{ name: "Delft Blue", hex: "#3B5C9E" }, { name: "Sage", hex: "#9CA877" }, { name: "Brick Red", hex: "#B14B3A" }],
    image: "https://images.unsplash.com/photo-1623310658847-33f12eaab710",
    alt: "Stack of folded heritage-print cotton hijabs on a pale surface.",
    description: "A folded set of heritage-print cotton hijabs, each with its own ornamental motif. Crisp, structured cotton that holds a fold and a wrap equally well." },

  { id: 27, brand: "Hijabia", name: "Ivory Goldline Belted Kaftan", category: "Kaftan", fabric: "Satin", price: 149, badge: "Limited",
    sizes: ["S", "M", "L"],
    colors: [{ name: "Ivory", hex: "#EDE6D6" }, { name: "Gold Cord", hex: "#C2A152" }],
    image: "https://images.unsplash.com/photo-1742384194806-2a87f385345f",
    alt: "Ivory jacquard kaftan with gold cord trim and a slim belt, shown chin down.",
    description: "An ivory jacquard kaftan edged in gold cord and cinched with a slim braided belt over a long bell-sleeved silhouette. A celebratory piece with a luminous, fully covering drape." },

  { id: 28, brand: "Hijabi MV", name: "Palm Lagoon Printed Scarf", category: "Scarf", fabric: "Georgette", price: 31,
    sizes: ["One Size", "Maxi (200x75cm)"],
    colors: [{ name: "Aqua", hex: "#54C7D8" }, { name: "Leaf Green", hex: "#8FC93A" }, { name: "Ivory", hex: "#F4F2EC" }],
    image: "https://images.unsplash.com/photo-1623832101624-ecd47c803527",
    alt: "Blue and green tropical leaf print scarf in a flatlay.",
    description: "A breezy georgette scarf in a watercolour palm print of aqua, green and ivory. Light and fluid, it brings holiday-ready freshness and a soft drape." },

  { id: 29, brand: "Hijabia", name: "Crimson Boucle Wool Coat", category: "Outerwear", fabric: "Wool", price: 122,
    sizes: ["S", "M", "L"],
    colors: [{ name: "Crimson", hex: "#C5341F" }, { name: "Brick Red", hex: "#A02C20" }, { name: "Burgundy", hex: "#6E1E22" }],
    image: "https://images.unsplash.com/photo-1635062562403-117becb17d3b",
    alt: "Red brushed boucle wool long coats with long sleeves on a rail.",
    description: "A statement coat in brushed boucle wool, in rich saturated reds. Long sleeves and a longline body deliver cosy, full coverage over a neutral inner dress." },

  { id: 30, brand: "Hijabi MV", name: "Jewel Weave Wool Wrap", category: "Shawl", fabric: "Wool", price: 64,
    sizes: ["Maxi (200x75cm)", "Oversized (200x100cm)"],
    colors: [{ name: "Midnight Blue", hex: "#2E3A56" }, { name: "Plum", hex: "#7A4A63" }, { name: "Antique Gold", hex: "#B59A5B" }],
    image: "https://images.unsplash.com/photo-1636545710627-ff66fa6b5500",
    alt: "Patterned blue and plum wool wrap draped as a styled still life.",
    description: "A statement wool wrap woven with shifting jewel tones of blue, plum and antique gold. Heavy enough for an elegant drape as an evening shawl or luxe oversized scarf." },

  { id: 31, brand: "Hijabia", name: "Marwa Draped Maxi Abaya", category: "Abaya", fabric: "Crepe", price: 124,
    sizes: ["54\"", "56\"", "58\"", "60\""],
    colors: [{ name: "Jet Black", hex: "#171717" }, { name: "Deep Espresso", hex: "#3B2F2A" }],
    image: "https://images.unsplash.com/photo-1686545232461-5399fb2e63c3",
    alt: "Long black modest maxi abaya seen from the back with long sleeves.",
    description: "An ankle-grazing draped maxi abaya in fluid opaque crepe with a subtle contrast back yoke. Long sleeves and a generous hem deliver elegant, fully covered styling." },

  { id: 32, brand: "Hijabi MV", name: "Atelier Chiffon Hijab Edit", category: "Hijab", fabric: "Chiffon", price: 27,
    sizes: ["One Size", "Long (180x65cm)"],
    colors: [{ name: "Lavender", hex: "#9B8BC4" }, { name: "Peach", hex: "#E7B79A" }, { name: "Petrol", hex: "#1E6E84" }, { name: "Tangerine", hex: "#E5621F" }],
    image: "https://images.unsplash.com/photo-1640767760729-7bfb6ce43ad4",
    alt: "Rolls of coloured chiffon hijab fabric on atelier shelves.",
    description: "An atelier wall of chiffon hijabs rolled and shelved by colour. Featherweight and fluid, this drape layers beautifully for an airy, elegant finish." },

  { id: 33, brand: "Hijabia", name: "Sahar Hooded Robe Kaftan", category: "Kaftan", fabric: "Crepe", price: 84,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [{ name: "Ivory", hex: "#EAE3D6" }, { name: "Warm Sand", hex: "#CDBFA6" }],
    image: "https://images.unsplash.com/photo-1648383452657-3be3b45a1b3f",
    alt: "Long hooded ivory robe kaftan on a wooden hanger with long sleeves.",
    description: "A cosy hooded robe-style kaftan with a generous wrap front, long sleeves and a relaxed full-length drape. The dense opaque fabric offers soft, fully covered comfort." },

  { id: 34, brand: "Hijabi MV", name: "Paisley Pashmina Scarf", category: "Scarf", fabric: "Viscose", price: 31,
    sizes: ["Maxi (200x75cm)", "Oversized (200x100cm)"],
    colors: [{ name: "Olive", hex: "#7E8B3D" }, { name: "Antique Rose", hex: "#B98598" }, { name: "Turquoise", hex: "#2BA6A0" }, { name: "Rust", hex: "#B5512C" }],
    image: "https://images.unsplash.com/photo-1517472292914-9570a594783b",
    alt: "Row of paisley-patterned pashmina scarves hanging side by side.",
    description: "Richly patterned paisley pashmina scarves hung in a graduated row of colour. Soft, warm viscose with intricate woven detail and generous drape." },

  { id: 35, brand: "Hijabia", name: "Belted Camel Wrap Coat", category: "Outerwear", fabric: "Wool", price: 126, badge: "Bestseller",
    sizes: ["S", "M", "L", "XL"],
    colors: [{ name: "Camel", hex: "#C19A6B" }, { name: "Tan", hex: "#B08A5E" }, { name: "Caramel", hex: "#A87545" }],
    image: "https://images.unsplash.com/photo-1666513241353-14a198830381",
    alt: "Camel wool wrap coat with a tie belt and long sleeves, cropped below the shoulders.",
    description: "A timeless camel wrap coat in soft wool, cinched with a self-tie belt. Long sleeves and a wrap-front silhouette give a flattering, fully covered line." },

  { id: 36, brand: "Hijabi MV", name: "Highland Knit Wrap", category: "Shawl", fabric: "Knit", price: 48, badge: "Bestseller",
    sizes: ["Standard (180x70cm)", "Oversized (200x100cm)"],
    colors: [{ name: "Slate", hex: "#6E7B82" }, { name: "Moss", hex: "#8AA13A" }, { name: "Dove", hex: "#AFB6B0" }],
    image: "https://images.unsplash.com/photo-1457545195570-67f207084966",
    alt: "Stack of folded chunky knit wraps in slate, moss and dove grey.",
    description: "Chunky cosy knit wraps, folded and ready to grab on a cool morning. Thick, soft and forgiving, equally at home as a shawl or a wrap-around blanket scarf." },

  { id: 37, brand: "Hijabia", name: "Noor Buttoned Coat Abaya", category: "Abaya", fabric: "Crepe", price: 112,
    sizes: ["52\"", "54\"", "56\"", "58\""],
    colors: [{ name: "Ink Black", hex: "#15161A" }, { name: "Charcoal", hex: "#3A3C40" }],
    image: "https://images.unsplash.com/photo-1730454809551-58c6afadec4c",
    alt: "Black buttoned coat-style abaya seen from behind with long sleeves.",
    description: "A structured coat-style abaya in opaque crepe with a buttoned back placket and tie waist. Long sleeves and a sweeping full-length hem give polished, fully covered appeal." },

  { id: 38, brand: "Hijabi MV", name: "Pastel Stripe Rolled Hijab Set", category: "Hijab", fabric: "Cotton", price: 25,
    sizes: ["Long (180x65cm)", "Standard (180x70cm)"],
    colors: [{ name: "Sky", hex: "#A9C7DE" }, { name: "Caramel", hex: "#C49A6C" }, { name: "Mauve", hex: "#C08AA0" }],
    image: "https://images.unsplash.com/photo-1638256049277-d405173a560b",
    alt: "Rolled striped pastel hijabs laid out in a flatlay with frayed ends.",
    description: "A flatlay of lightly striped hijabs rolled and fanned out with soft frayed ends. Fine, breezy cotton in gentle pastels for an understated, polished wrap." },

  { id: 39, brand: "Hijabia", name: "Hana Wrap Kimono Robe", category: "Kaftan", fabric: "Satin", price: 89,
    sizes: ["XS", "S", "M", "L"],
    colors: [{ name: "Coral Bloom", hex: "#E0876F" }, { name: "Sand Beige", hex: "#D8C4A6" }],
    image: "https://images.unsplash.com/photo-1759579470279-0a647e2968b9",
    alt: "Printed satin kimono robe on a hanger with long sleeves and full coverage.",
    description: "A printed satin kimono-style robe with a classic wide overlap front, tie waist and long flowing sleeves. The opaque finish and full length make it an elegant covered layer." },

  { id: 40, brand: "Hijabia", name: "Longline Knit Cardigan Coat", category: "Outerwear", fabric: "Cotton", price: 89,
    sizes: ["S", "M", "L", "XL"],
    colors: [{ name: "Oatmeal", hex: "#D8CCB6" }, { name: "Greige", hex: "#B6AB99" }, { name: "Soft Grey", hex: "#9D988E" }],
    image: "https://images.unsplash.com/photo-1617669776234-fc5a89eb8f19",
    alt: "Long oatmeal knit open cardigan coat with long sleeves, shown from behind.",
    description: "A soft longline knit cardigan that works as a lightweight open coat. Long sleeves and a below-the-hip length offer relaxed modest coverage over a tunic and trousers." },

  { id: 41, brand: "Hijabi MV", name: "Oatmeal Cable Knit Shawl", category: "Shawl", fabric: "Cashmere blend", price: 62,
    sizes: ["Standard (180x70cm)", "Long (180x65cm)"],
    colors: [{ name: "Oatmeal", hex: "#D8C7AC" }, { name: "Cream", hex: "#E7DEC8" }],
    image: "https://images.unsplash.com/photo-1491245257527-395e9c480145",
    alt: "Cream cable-knit shawl loosely draped on weathered wood.",
    description: "A soft cable-knit shawl in warm oatmeal with a plush cashmere-blend hand-feel. It folds compact for travel and opens into a generous, shape-holding wrap." },

  { id: 42, brand: "Hijabia", name: "Aaliyah Khimar Abaya Set", category: "Abaya", fabric: "Georgette", price: 128,
    sizes: ["54\"", "56\"", "58\"", "60\""],
    colors: [{ name: "Forest Teal", hex: "#2E4843" }, { name: "Deep Pine", hex: "#243B34" }],
    image: "https://images.unsplash.com/photo-1589530223636-7befefdaee12",
    alt: "Dark teal khimar and abaya gown with long sleeves, shown from behind.",
    description: "A two-piece khimar and abaya gown in opaque georgette, offering full head-to-floor coverage with long sleeves and a draped cape-like overlay for maximum modesty." },

  { id: 43, brand: "Hijabia", name: "Kyoto Ceremonial Kaftan", category: "Kaftan", fabric: "Jacquard", price: 132,
    sizes: ["M", "L", "XL"],
    colors: [{ name: "Midnight Floral", hex: "#2A2440" }, { name: "Antique Gold", hex: "#B08A4A" }],
    image: "https://images.unsplash.com/photo-1664362223041-89805535a89c",
    alt: "Ornate long ceremonial kaftan displayed flat with wide long sleeves.",
    description: "An ornate full-length ceremonial kaftan in richly patterned opaque jacquard, with sweeping long sleeves and intricate floral motifs. A statement covered piece with heritage detailing." },

  { id: 44, brand: "Hijabia", name: "Heritage Knit Winter Coat", category: "Outerwear", fabric: "Wool", price: 118,
    sizes: ["S", "M", "L", "XL"],
    colors: [{ name: "Charcoal Grey", hex: "#4A4A4C" }, { name: "Deep Red", hex: "#8C2B2B" }, { name: "Cream", hex: "#E8E0CE" }],
    image: "https://images.unsplash.com/photo-1766048282995-f27184da237c",
    alt: "Heavy knit and wool winter long coats with long sleeves on a store rail.",
    description: "A heavyweight heritage-knit winter coat with long sleeves, a shawl-style collar and a longline body for thick, full modest coverage, with sherpa-lined warmth." },

  { id: 45, brand: "Hijabi MV", name: "Neutral Cashmere Wrap", category: "Shawl", fabric: "Cashmere blend", price: 54,
    sizes: ["One Size", "Maxi (200x75cm)"],
    colors: [{ name: "Taupe", hex: "#A99784" }, { name: "Stone", hex: "#BBB1A1" }, { name: "Espresso", hex: "#5A4A3C" }],
    image: "https://images.unsplash.com/photo-1603906650843-b58e94d9df4d",
    alt: "Neutral cashmere-blend wraps in taupe, stone and espresso on a rail.",
    description: "A capsule of neutral cashmere-blend wraps in taupe, stone and espresso. Lightweight yet warm, they slip easily from a folded hijab to a full shoulder wrap." },

  { id: 46, brand: "Hijabia", name: "Inara Gown Abaya", category: "Abaya", fabric: "Crepe", price: 102,
    sizes: ["54\"", "56\"", "58\""],
    colors: [{ name: "Black", hex: "#181818" }, { name: "Blush", hex: "#D9B7A8" }],
    image: "https://images.unsplash.com/photo-1686545231794-4ad459f1a5d6",
    alt: "Long black gown abaya with an embroidered shoulder drape, shown from behind.",
    description: "A ceremonial floor-length gown abaya in opaque crepe with an embroidered contrast shoulder drape. Long sleeves and a full-length cut make it a refined occasion piece." },

  { id: 47, brand: "Hijabia", name: "Safiya Flared Maxi Abaya", category: "Abaya", fabric: "Crepe", price: 99,
    sizes: ["52\"", "54\"", "56\"", "58\""],
    colors: [{ name: "Pure Black", hex: "#1C1C1C" }, { name: "Slate Navy", hex: "#2C3140" }],
    image: "https://images.unsplash.com/photo-1573999615713-49f8783e6614",
    alt: "Long flared black maxi abaya with long sleeves, shown from behind.",
    description: "A softly flared floor-length maxi abaya in opaque crepe with a gathered yoke and gently widening hem. Long sleeves and a fluid drape give a graceful, fully covered finish." }
];
